---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
knitr::opts_knit$set(root.dir = '/home/yuzhao1/gca/yuzhao1/work/gca_rna/')
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')

library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
source('~/yuzhao1/scripts/plot.R')
source('~/yuzhao1/work/final_GCArna/scripts/gca_colors.R')
source('~/yuzhao1/work/final_GCArna/scripts/gca_markers.R')
```

```{r}
epithelial <- readRDS('~/yuzhao1/work/final_GCArna/annotation/rds/epithelial4.rds')
```


```{r, include = F, eval=F}
# epithelial <- readRDS('~/yuzhao1/work/final_GCArna/annotation/rds/epithelial3.rds')
# epithelial3_ti <- subset(epithelial, biopsy_location == 'TI')
# epithelial3_ac <- subset(epithelial, biopsy_location == 'AC')
```

```{r, eval=F}
# # save epithelial2 again after second round of processing
# saveRDS(epithelial, '~/yuzhao1/work/final_GCArna/annotation/rds/epithelial3.rds')
# saveRDS(epithelial3_ac, '~/yuzhao1/work/final_GCArna/annotation/rds/epithelial3_AC.rds')
# saveRDS(epithelial3_ti, '~/yuzhao1/work/final_GCArna/annotation/rds/epithelial3_TI.rds')
```

```{r, eval=F}
epithelial_ti <- readRDS('~/yuzhao1/work/final_GCArna/annotation/rds/epithelial3_TI.rds')
epithelial_ac <- readRDS('~/yuzhao1/work/final_GCArna/annotation/rds/epithelial3_AC.rds')
```


```{r}
epithelial <- merge(epithelial_ac, y = epithelial_ti, add.cell.ids = NULL, project = "epithelial")
```

```{r}
columns_to_remove <- grep("seurat_cluster", names(epithelial@meta.data))
epithelial@meta.data <- epithelial@meta.data[,-columns_to_remove]
columns_to_remove <- grep("RNA_snn_", names(epithelial@meta.data))
epithelial@meta.data <- epithelial@meta.data[,-columns_to_remove]
```


```{r}
# save epithelial2 again after second round of processing
epithelial$lineage <- 'epithelial'
write.table(epithelial@meta.data, '~/yuzhao1/work/final_GCArna/annotation/rds/epithelial4_Metadata.csv', sep = ',')
saveRDS(epithelial, '~/yuzhao1/work/final_GCArna/annotation/rds/epithelial4.rds')
saveRDS(epithelial_ac, '~/yuzhao1/work/final_GCArna/annotation/rds/epithelial4_AC.rds')
saveRDS(epithelial_ti, '~/yuzhao1/work/final_GCArna/annotation/rds/epithelial4_TI.rds')
```


### workflow


```{r, include = F, eval=F}
epithelial <- NormalizeData(epithelial)
epithelial <- FindVariableFeatures(epithelial, selection.method = "vst", nfeatures = 2000)
epithelial <- ScaleData(epithelial, vars.to.regress = c('percent.mt', 'nCount_RNA', 'CC.Difference'))
epithelial <- RunPCA(epithelial, npcs = 50)

epithelial <- FindNeighbors(epithelial, reduction = 'pca', dims = 1:25)

epithelial <- RunUMAP(epithelial,  dims = 1:25, reduction = 'pca', reduction.name = 'pca_umap',
                  min.dist = 0.3, n.neighbors = 50, seed.use = 5,
                  reduction.key = 'UMAP_')

```

```{r}
# epithelial <- RunHarmony(epithelial, group.by.vars = 'Patient_ID', max.iter.harmony = 10)
# epithelial <- FindNeighbors(epithelial, reduction = 'harmony', dims = 1:30)
# epithelial <- RunUMAP(epithelial,  dims = 1:30, reduction = 'harmony', reduction.name = 'harmony_umap',
#                       min.dist = 0.5, n.neighbors = 50, seed.use = 5,
#                       reduction.key = 'UMAP_')
```



### Check clustering results


```{r, fig.height=9, fig.width=8.5}
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_2
df$cluster_name <- epithelial$anno2
pdf('~/yuzhao1/work/final_GCArna/annotation/plots/epithelial3/umap_anno2.pdf', height = 8, width = 7)
plot_df_umap_custom(df, show.label = 'name')
dev.off()
```



```{r, fig.height=13, fig.width=12}
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_2
df$cluster_name <- epithelial$anno2
pdf('~/yuzhao1/work/final_GCArna/annotation/plots/epithelial3/umap_epithelial_loc_anno2.pdf', height = 8.5, width = 12)
plot_df_umap_custom(df, show.label = 'name') +
  facet_wrap(~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()
```

```{r, fig.height=13, fig.width=12}
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_2
df$cluster_name <- epithelial$anno2
pdf('~/yuzhao1/work/final_GCArna/annotation/plots/epithelial3/umap_epithelial_disease_anno2.pdf', height = 8.5, width = 12)
plot_df_umap_custom(df, show.label = 'name') +
  facet_wrap(~ disease_status) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
dev.off()
```

```{r, fig.height=7, fig.width=10}
feature <- 'AQP8'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()

plot_df_umap_custom(df, plot_feature = T) +
  facet_wrap(~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
```

```{r, fig.height=7, fig.width=10}
feature <- 'FABP6'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()

plot_df_umap_custom(df, plot_feature = T) +
  facet_wrap(~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
```

```{r, fig.height=7, fig.width=10}
feature <- 'MUC2'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()

plot_df_umap_custom(df, plot_feature = T) +
  facet_wrap(~ disease_status) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
```

```{r, fig.height=7, fig.width=10}
feature <- 'AQP8'
df <- data.frame(epithelial@meta.data)
df$embedding1 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(epithelial@reductions$pca_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(epithelial, feature) %>% unlist()

plot_df_umap_custom(df, plot_feature = T) +
  facet_wrap(~ disease_status) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
```









