---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')

library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(harmony)
library(Seurat)
source('~/yuzhao1/scripts/plot.R')
source('~/yuzhao1/work/final_GCArna/scripts/gca_colors.R')
source('~/yuzhao1/work/final_GCArna/scripts/gca_markers.R')
```

```{r, include = F, eval=F}
stromal <- readRDS('~/yuzhao1/work/final_GCArna/annotation/rds/stromal2.rds')
```

```{r}
stromal$lineage <- 'stromal'
saveRDS(stromal, '~/yuzhao1/work/final_GCArna/annotation/rds/stromal2.rds')
write.table(stromal@meta.data, '~/yuzhao1/work/final_GCArna/annotation/rds/stromal2_metadata.csv', sep = ',')
```


```{r}
# decide whether to remove clusters
columns_to_remove <- grep("seurat_cluster", names(stromal@meta.data))
stromal@meta.data <- stromal@meta.data[,-columns_to_remove]
columns_to_remove <- grep("RNA_snn_", names(stromal@meta.data))
stromal@meta.data <- stromal@meta.data[,-columns_to_remove]
```

```{r}
# filter LQ cells from previous clustering results, and then remove precious labels, from stromal1 to stromal2
# LQ: remove stromal-epithelial doublets
xx <- Cells(stromal)[which(!stromal$seurat_clusters_res0.3 %in% c(10, 12))]
stromal_filtered <- subset(stromal, cells = xx)
columns_to_remove <- grep("seurat_cluster", names(stromal_filtered@meta.data))
stromal_filtered@meta.data <- stromal_filtered@meta.data[,-columns_to_remove]
columns_to_remove <- grep("RNA_snn_", names(stromal_filtered@meta.data))
stromal_filtered@meta.data <- stromal_filtered@meta.data[,-columns_to_remove]
```

```{r}
ref <- readRDS('~/yuzhao1/work/final_RC2rna/annotation/rds/others3.rds')
anchors <- FindTransferAnchors(reference = ref, query = stromal, dims = 1:25, reference.reduction = "pca")
predictions <- TransferData(anchorset = anchors, refdata = ref$anno1, dims = 1:25)
stromal$predicted.anno1 <- mapvalues(Cells(stromal), rownames(predictions), predictions$predicted.id)
```

```{r}
df_annotation_res0.3 <- list(
'0' = 'Fibroblast1',
'1' = 'Arterial',
'2' = 'Fibroblast4',
'3' = 'Fibroblast3',
'4' = 'Venous',
'5' = 'Pericyte',
'6' = 'Myofibroblast',
'7' = 'Glial',
'8' = 'Fibroblast2',
'9' = 'Lymphatic endothelium',
'10' = 'Contractile Pericyte')

stromal$anno1 <- unlist(mapvalues(as.character(stromal$seurat_clusters_res0.3), from = names(df_annotation_res0.3), to = df_annotation_res0.3))
stromal$anno2 <- stromal$anno1

```



### workflow


```{r, include = F, eval=F}
stromal <- NormalizeData(stromal)
stromal <- FindVariableFeatures(stromal, selection.method = "vst", nfeatures = 2000)
stromal <- ScaleData(stromal, vars.to.regress = c('percent.mt', 'nCount_RNA', 'CC.Difference'))
stromal <- RunPCA(stromal, npcs = 50)

stromal <- FindNeighbors(stromal, reduction = 'pca', dims = 1:30)

stromal <- RunUMAP(stromal,  dims = 1:30, reduction = 'pca', reduction.name = 'pca_umap',
                  min.dist = 0.3, n.neighbors = 30, seed.use = 5,
                  reduction.key = 'UMAP_')

stromal <- FindClusters(stromal, resolution = 0.2)
stromal$seurat_clusters_res0.2 <- Idents(stromal)

stromal <- FindClusters(stromal, resolution = 0.3)
stromal$seurat_clusters_res0.3 <- Idents(stromal)

stromal <- FindClusters(stromal, resolution = 0.5)
stromal$seurat_clusters_res0.5 <- Idents(stromal)

stromal <- FindClusters(stromal, resolution = 0.8)
stromal$seurat_clusters_res0.8 <- Idents(stromal)

stromal <- FindClusters(stromal, resolution = 1)
stromal$seurat_clusters_res1 <- Idents(stromal)


```

```{r}
ElbowPlot(stromal, ndims = 50)
```

```{r}
# 10 16 17 18
xx <- FindMarkers(stromal, ident.1 = 18, min.pct = 0.2, logfc.threshold = 1, group.by = 'seurat_clusters_res0.5')
View(xx)
```

```{r}
xx <- list()
for(cluster in c(8,5,0)){
  xx[[cluster]] <- FindMarkers(stromal, ident.1 = cluster, min.pct = 0.2, logfc.threshold = 1, group.by = 'seurat_clusters_res0.8')
  saveRDS(xx[[cluster]], paste0('~/yuzhao1/work/final_GCArna/annotation/markers/stromal2_res0.8/cluster_', cluster, '.rds'))
}
```

```{r}
# remove 22
cluster <- '7'
View(readRDS(paste0('~/yuzhao1/work/final_GCArna/annotation/markers/stromal1_res0.8/cluster_', cluster, '.rds')))
```




### Check clustering results

```{r}
df <- data.frame(stromal@meta.data)
df$embedding1 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_2
df$cluster_name <- stromal$anno1
plot_df_umap_custom(df, show.label = 'name')
```

```{r}
ss <- subset(stromal, cells = Cells(ref)[which(ref$biopsy_location %in% c('AC', 'TI'))])
ss$anno1_true <- mapvalues(Cells(ss), Cells(ss), ref@meta.data[Cells(ss), 'anno1'])
```

```{r}
df <- data.frame(ss@meta.data)
df$embedding1 <- data.frame(ss@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(ss@reductions$pca_umap@cell.embeddings)$UMAP_2
df$cluster_name <- ss$anno1_true
plot_df_umap_custom(df, show.label = 'name')
```


```{r, fig.height=8, fig.width=7}
df <- data.frame(stromal@meta.data)
df$embedding1 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_2
df$cluster_name <- stromal$predicted.anno1
plot_df_umap_custom(df, show.label = 'name')
```

```{r, fig.height=8, fig.width=7}
df <- data.frame(stromal@meta.data)
df$embedding1 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_2
df$cluster_name <- stromal$seurat_clusters_res0.3
plot_df_umap_custom(df, show.label = 'name')
```

```{r, fig.height=7, fig.width=10}
df <- data.frame(stromal@meta.data)
df$embedding1 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_2
df$cluster_name <- stromal$anno1
plot_df_umap_custom(df, show.label = 'name') +
  facet_wrap(~ biopsy_location) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
```

```{r, fig.height=7, fig.width=10}
df <- data.frame(stromal@meta.data)
df$embedding1 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_2
df$cluster_name <- stromal$anno1
plot_df_umap_custom(df, show.label = 'name') +
  facet_wrap(~ disease_status) +
  theme(
    strip.background = element_rect(fill = "white", colour = "white"),
    strip.text = element_text(size = 12)
  )
```

#### Check specific markers

```{r}
genes_to_plot <- c(unlist(gca_rna.stromal.markers), 'IGHA1', 'CPA3')
for (feature in genes_to_plot){
  df <- data.frame(stromal@meta.data)
  df$embedding1 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_1
  df$embedding2 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_2
  df$feature_to_plot <- FetchData(stromal, feature) %>% unlist()
  png(paste0('~/yuzhao1/work/final_GCArna/annotation/plots/stromal/singlegene/', feature, '.png'), res = 300, height = 2000, width = 2000)
  p <-   plot_df_umap_custom(df, plot_feature = T)
  print(p)
  dev.off()
}
```

```{r}
feature <- 'NRG1'
df <- data.frame(stromal@meta.data)
df$embedding1 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(stromal, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r}
feature <- 'CD3D'
df <- data.frame(stromal@meta.data)
df$embedding1 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_1
df$embedding2 <- data.frame(stromal@reductions$pca_umap@cell.embeddings)$UMAP_2
df$feature_to_plot <- FetchData(stromal, feature) %>% unlist()
plot_df_umap_custom(df, plot_feature = T)
```

```{r}
VlnPlot(object = stromal, features = 'IGHA1', group.by = 'seurat_clusters_res1.5')
```











