#!/bin/bash
sbatch -J  HA01-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA01-AC 
sbatch -J  HA01-TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA01-TI 
sbatch -J  HA02-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA02-AC 
sbatch -J  HA02-TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA02-TI 
sbatch -J  HA04-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA04-AC 
sbatch -J  HA04-TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA04-TI 
sbatch -J  HA07-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA07-AC 
sbatch -J  HA07-TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA07-TI 
sbatch -J  HA08-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA08-AC 
sbatch -J  HA08-TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA08-TI 
sbatch -J  HA11-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA11-AC 
sbatch -J  HA11-TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA11-TI 
sbatch -J  HA14-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA14-AC 
sbatch -J  HA14-TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA14-TI 
sbatch -J  HA16-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA16-AC 
sbatch -J  HA17-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA17-AC 
sbatch -J  HA19-TI-adj  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA19-TI-adj 
sbatch -J  HA19-TI-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA19-TI-inf 
sbatch -J  HA19-TI-non  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA19-TI-non 
sbatch -J  HA22-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA22-AC 
sbatch -J  HA26-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA26-AC 
sbatch -J  HA26-TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA26-TI 
sbatch -J  HA27-AC-noninf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA27-AC-noninf 
sbatch -J  HA27-TI-adjinf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA27-TI-adjinf 
sbatch -J  HA27-TI-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA27-TI-inf 
sbatch -J  HA27-TI-noninf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA27-TI-noninf 
sbatch -J  HA30-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA30-AC 
sbatch -J  HA31-AC-noninf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA31-AC-noninf 
sbatch -J  HA31-TI-noninf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA31-TI-noninf 
sbatch -J  HA35-TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA35-TI 
sbatch -J  HA36-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA36-AC 
sbatch -J  HA36-TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA36-TI 
sbatch -J  HA37-AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA37-AC 
sbatch -J  HA37-TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA37-TI 
sbatch -J  HA38TI-ad  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA38TI-ad 
sbatch -J  HA38TI-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA38TI-inf 
sbatch -J  HA41AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA41AC 
sbatch -J  HA41TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA41TI 
sbatch -J  HA43TI-ad  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA43TI-ad 
sbatch -J  HA43TI-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA43TI-inf 
sbatch -J  HA48TI-ad  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA48TI-ad 
sbatch -J  HA48TI-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA48TI-inf 
sbatch -J  HA49AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA49AC 
sbatch -J  HA49TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA49TI 
sbatch -J  HA50AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA50AC 
sbatch -J  HA50TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA50TI 
sbatch -J  HA51AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA51AC 
sbatch -J  HA51TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA51TI 
sbatch -J  HA52AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA52AC 
sbatch -J  HA54AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA54AC 
sbatch -J  HA54TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA54TI 
sbatch -J  HA55AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA55AC 
sbatch -J  HA55TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA55TI 
sbatch -J  HA56TI-ad  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA56TI-ad 
sbatch -J  HA56TI-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA56TI-inf 
sbatch -J  HA57AC-ad  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA57AC-ad 
sbatch -J  HA57AC-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA57AC-inf 
sbatch -J  HA59TI-ad  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA59TI-ad 
sbatch -J  HA59TI-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA59TI-inf 
sbatch -J  HA60TI-ad  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA60TI-ad 
sbatch -J  HA60TI-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA60TI-inf 
sbatch -J  HA61TI-ad  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA61TI-ad 
sbatch -J  HA61TI-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA61TI-inf 
sbatch -J  HA62AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA62AC 
sbatch -J  HA62TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA62TI 
sbatch -J  HA63AC-ad  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA63AC-ad 
sbatch -J  HA63AC-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA63AC-inf 
sbatch -J  HA65AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA65AC 
sbatch -J  HA65TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA65TI 
sbatch -J  HA66AC-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA66AC-inf 
sbatch -J  HA66AC_ad  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA66AC_ad 
sbatch -J  HA68TI-ad  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA68TI-ad 
sbatch -J  HA68TI-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA68TI-inf 
sbatch -J  HA70TI-ad  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA70TI-ad 
sbatch -J  HA70TI-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA70TI-inf 
sbatch -J  HA79TI-ad  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA79TI-ad 
sbatch -J  HA79TI-inf  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/HA79TI-inf 
sbatch -J  OR07-TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/OR07-TI 
sbatch -J  OR95AC  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/OR95AC 
sbatch -J  OR95TI  velocyto.batch  ~/yuzhao1/work/final_GCArna/upstream/OR95TI