cd ~/yuzhao1/work/final_GCAatac/18glimpse
sbatch -J C1 --time=36:00:00 --mem=5Gb --output=3.1log/C1.out --error=3.1log/C1.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C1.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C1-AC-Control/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C1-TI-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C1.bam'
sbatch -J C2 --time=36:00:00 --mem=5Gb --output=3.1log/C2.out --error=3.1log/C2.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C2.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C2-AC-Control/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C2-TI-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C2.bam'
sbatch -J C3 --time=36:00:00 --mem=5Gb --output=3.1log/C3.out --error=3.1log/C3.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C3.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C3-AC-Control/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C3-TI-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C3.bam'
sbatch -J C4 --time=36:00:00 --mem=5Gb --output=3.1log/C4.out --error=3.1log/C4.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C4.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C4-TI-Control/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C4-AC-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C4.bam'
sbatch -J C5 --time=36:00:00 --mem=5Gb --output=3.1log/C5.out --error=3.1log/C5.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C5.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C5-AC-Control/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C5-TI-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C5.bam'
sbatch -J C6 --time=36:00:00 --mem=5Gb --output=3.1log/C6.out --error=3.1log/C6.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C6.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C6-AC-Control/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C6-TI-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C6.bam'
sbatch -J C7 --time=36:00:00 --mem=5Gb --output=3.1log/C7.out --error=3.1log/C7.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C7.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C7-AC-Control/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C7-TI-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C7.bam'
sbatch -J P3 --time=36:00:00 --mem=5Gb --output=3.1log/P3.out --error=3.1log/P3.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P3.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P3-AC-CDnonInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P3.bam'
sbatch -J P4 --time=36:00:00 --mem=5Gb --output=3.1log/P4.out --error=3.1log/P4.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P4.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P4-AC-CDnonInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P4.bam'
sbatch -J P5 --time=36:00:00 --mem=5Gb --output=3.1log/P5.out --error=3.1log/P5.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P5.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P5-TI-CDadjInf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P5-TI-CDinf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P5-TI-CDnonInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P5.bam'
sbatch -J P6 --time=36:00:00 --mem=5Gb --output=3.1log/P6.out --error=3.1log/P6.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P6.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P6-AC-CDnonInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P6.bam'
sbatch -J P7 --time=36:00:00 --mem=5Gb --output=3.1log/P7.out --error=3.1log/P7.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P7.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P7-TI-CDnonInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P7.bam'
sbatch -J P8 --time=36:00:00 --mem=5Gb --output=3.1log/P8.out --error=3.1log/P8.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P8.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P8-AC-CDnonInf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P8-TI-CDadjInf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P8-TI-CDinf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P8-TI-CDnonInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P8.bam'
sbatch -J P9 --time=36:00:00 --mem=5Gb --output=3.1log/P9.out --error=3.1log/P9.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P9.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P9-AC-CDnonInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P9.bam'
sbatch -J P10 --time=36:00:00 --mem=5Gb --output=3.1log/P10.out --error=3.1log/P10.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P10.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P10-AC-CDnonInf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P10-TI-CDnonInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P10.bam'
sbatch -J P11 --time=36:00:00 --mem=5Gb --output=3.1log/P11.out --error=3.1log/P11.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P11.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P11-TI-CDnonInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P11.bam'
sbatch -J P12 --time=36:00:00 --mem=5Gb --output=3.1log/P12.out --error=3.1log/P12.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P12.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P12-AC-CDnonInf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P12-TI-CDnonInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P12.bam'
sbatch -J P13 --time=36:00:00 --mem=5Gb --output=3.1log/P13.out --error=3.1log/P13.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P13.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P13-AC-CDnonInf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P13-TI-CDnonInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P13.bam'
sbatch -J P14 --time=36:00:00 --mem=5Gb --output=3.1log/P14.out --error=3.1log/P14.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P14.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P14-TI-CDadjInf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P14-TI-CDinf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P14.bam'
sbatch -J P15 --time=36:00:00 --mem=5Gb --output=3.1log/P15.out --error=3.1log/P15.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P15.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P15-TI-CDadjInf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P15-TI-CDinf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P15.bam'
sbatch -J C9 --time=36:00:00 --mem=5Gb --output=3.1log/C9.out --error=3.1log/C9.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C9.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C9-AC-Control/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C9-TI-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C9.bam'
sbatch -J C10 --time=36:00:00 --mem=5Gb --output=3.1log/C10.out --error=3.1log/C10.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C10.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C10-TI-Control/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C10-AC-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C10.bam'
sbatch -J C11 --time=36:00:00 --mem=5Gb --output=3.1log/C11.out --error=3.1log/C11.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C11.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C11-AC-Control/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C11-TI-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C11.bam'
sbatch -J C12 --time=36:00:00 --mem=5Gb --output=3.1log/C12.out --error=3.1log/C12.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C12.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C12-AC-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C12.bam'
sbatch -J C13 --time=36:00:00 --mem=5Gb --output=3.1log/C13.out --error=3.1log/C13.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C13.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C13-TI-Control/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C13-AC-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C13.bam'
sbatch -J C14 --time=36:00:00 --mem=5Gb --output=3.1log/C14.out --error=3.1log/C14.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C14.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C14-AC-Control/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C14-TI-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C14.bam'
sbatch -J P18 --time=36:00:00 --mem=5Gb --output=3.1log/P18.out --error=3.1log/P18.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P18.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P18-TI-CDadjInf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P18-TI-CDinf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P18.bam'
sbatch -J P19 --time=36:00:00 --mem=5Gb --output=3.1log/P19.out --error=3.1log/P19.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P19.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P19-AC-CDinf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P19-AC-CDadjInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P19.bam'
sbatch -J P20 --time=36:00:00 --mem=5Gb --output=3.1log/P20.out --error=3.1log/P20.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P20.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P20-TI-CDinf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P20-TI-CDadjInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P20.bam'
sbatch -J P21 --time=36:00:00 --mem=5Gb --output=3.1log/P21.out --error=3.1log/P21.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P21.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P21-TI-CDinf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P21-TI-CDadjInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P21.bam'
sbatch -J C15 --time=36:00:00 --mem=5Gb --output=3.1log/C15.out --error=3.1log/C15.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C15.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C15-TI-Control/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C15-AC-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C15.bam'
sbatch -J C16 --time=36:00:00 --mem=5Gb --output=3.1log/C16.out --error=3.1log/C16.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C16.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C16-TI-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C16.bam'
sbatch -J P26 --time=36:00:00 --mem=5Gb --output=3.1log/P26.out --error=3.1log/P26.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P26.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P26-TI-CDinf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P26-TI-CDadjInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P26.bam'
sbatch -J P27 --time=36:00:00 --mem=5Gb --output=3.1log/P27.out --error=3.1log/P27.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P27.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P27-TI-CDinf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P27-TI-CDadjInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P27.bam'
sbatch -J P2 --time=36:00:00 --mem=5Gb --output=3.1log/P2.out --error=3.1log/P2.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P2.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P2-TI-CDnonInf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P2.bam'
sbatch -J C17 --time=36:00:00 --mem=5Gb --output=3.1log/C17.out --error=3.1log/C17.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C17.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/C17-AC-Control/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/C17.bam'
sbatch -J P29 --time=36:00:00 --mem=5Gb --output=3.1log/P29.out --error=3.1log/P29.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P29.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P29-AC-CDadjInf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P29-AC-CDinf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P29.bam'
sbatch -J P30 --time=36:00:00 --mem=5Gb --output=3.1log/P30.out --error=3.1log/P30.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P30.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P30-AC-CDadjInf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P30-AC-CDinf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P30.bam'
sbatch -J P31 --time=36:00:00 --mem=5Gb --output=3.1log/P31.out --error=3.1log/P31.err --account=pi-spott  -p spott -c 1 --wrap='samtools merge -o /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P31.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P31-AC-CDadjInf/outs/possorted_bam.bam /project/spott/yuzhao1/GEO_GCAatac/cellranger_output/P31-AC-CDinf/outs/possorted_bam.bam
samtools index  /project/gca/yuzhao1/work/final_GCAatac/18glimpse/3.1patient_bam_merge/P31.bam'
