---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(motifbreakR)
library(SNPlocs.Hsapiens.dbSNP150.GRCh38) 
library(BSgenome.Hsapiens.UCSC.hg38)     
library(BSgenome)
library(plyr)
library(dplyr)
library(stringr)
library(tibble)
library(Seurat)
library(ArchR)
source('~/yuzhao1/work/atac_gca2024/scripts/gca_colors.R')
source('~/yuzhao1/work/final_GCArna/scripts/gca_markers.R')
out.dir <- '~/yuzhao1/work/atac_gca2024/0manu/plots/10mashQTL_motifBreak_part1/'
```

```{r}
# TF
df_TF_regulator <- readRDS('/project/gca/yuzhao1/work/atac_gca2024/5TF/output/union/regulator_df_anno1_inflammation_status_location_cor0.4_delta0.25.rds')
TF_positive <- df_TF_regulator[df_TF_regulator$TFRegulator=='Positive', 'cisbp_matchName']

# motif breakR
motif.breaks.all_unique <- readRDS('~/yuzhao1/work/atac_gca2024/26motif_disruption3/3results_summary/motif.breaks.all_unique.rds')
celltypes <- readLines('~/yuzhao1/work/atac_gca2024/26motif_disruption3/00celltypes.txt')
score.dir <- '~/yuzhao1/work/atac_gca2024/26mash3/3disruption_effect_cor_mashQTL/'

```


# correlation of motif disruption score versus effect size

```{r}
tfs <- intersect(unique(motif.breaks.all_unique$geneSymbol), TF_positive)
df <- data.frame(matrix(0, nrow = length(tfs), ncol = length(celltypes)))
rownames(df) <- tfs
colnames(df) <- celltypes
df_cor <- df
df_p <- df
```

```{r}
# read cor values, adjust p values
for (ct in celltypes) {
  row_id_tested <- c() # this is to help adjust p value (based on p values that are calculated)
  for (tf in tfs) {
    
    if(!file.exists(paste0(score.dir, ct, '/', tf, '.rds'))){
      df_cor[tf, ct] <- 0
      df_p[tf, ct] <- 1
      next
    }
    
    xx <- readRDS(paste0(score.dir, ct, '/', tf, '.rds'))
    if(length(xx) == 1){ # this mean it is the text i set, not a test result
      df_cor[tf, ct] <- 0
      df_p[tf, ct] <- 1
      next
    }
    
    row_id_tested <- c(row_id_tested, tf)
    df_cor[tf, ct] <- xx$estimate %>% as.numeric()
    df_p[tf, ct] <- xx$p.value %>% as.numeric()
  }
  p_values_original <- df_p[row_id_tested, ct]
  p_values_adjusted <- p.adjust(p_values_original, method = 'BH')
  df_p[row_id_tested, ct] <- p_values_adjusted
}
df_cor <- df_cor %>% na.replace(0)
df_p <- df_p %>% na.replace(1)
```


```{r}
# change cor values to 0 if adjp>adjp_threshold, not filtering out negative corrs
df_cor_plot <- df_cor
adjp_threshold <- 0.05

for (ct in celltypes){
  for (tf in tfs){
    if(df_p[tf, ct] > adjp_threshold){
      df_cor_plot[tf, ct] <- 0
    }
  }
}

df_cor_plot <- df_cor_plot[rownames(df_cor_plot) %in% TF_positive,]

# only plot the TFs with at least one significant value
df_cor_plot <- df_cor_plot[rowSums(df_cor_plot) > 0, ]
```

```{r}
library(circlize)
library(ComplexHeatmap)
df <- df_cor_plot
ct_order <- colnames(df)[order(match(colnames(df), names(gca_colors_atac_union_anno1)))]
df <- df[, ct_order]
df[df == "Too few QTLs"] <- 0
df2 <- data.frame(apply(df, 2, function(x) as.numeric(as.character(x))))
rownames(df2) <- rownames(df)
df <- t(df2)
```

```{r}
transposed_df <- t(df)
# scaled_df <- scale(transposed_df)
set.seed(6)  
num_clusters <- 8
kmeans_result <- kmeans(transposed_df, centers = num_clusters)
cluster_assignments <- kmeans_result$cluster
```

```{r}
# Unique clusters
clusters <- 1:num_clusters

# Initialize a vector to store the row assignment for each cluster
cluster_row_assignment <- setNames(rep(NA, length(clusters)), clusters)

# Calculate the mean for each cluster in each row and find the row with the highest mean
for (cluster in clusters) {
  # Columns belonging to the current cluster
  cluster_cols <- names(cluster_assignments)[cluster_assignments == cluster]
  
  # Calculate the mean for these columns in each row
  cluster_means <- apply(df[, cluster_cols, drop = FALSE], 1, mean)
  
  # Find the row with the maximum mean
  cluster_row_assignment[[cluster]] <- which.max(cluster_means)
}


# sort clusters by row_assignment
xx <- names(cluster_row_assignment)[order(cluster_row_assignment, decreasing = F)]
ordered_columns <- unlist(lapply(xx, function(cluster) {
  names(cluster_assignments)[cluster_assignments == cluster]
}))
df <- df[, ordered_columns]
```

```{r}
# remove cell types that don't have a TF represented
df <- df[rowSums2(df) > 0,]
```


```{r}
color = rev(c('#67001f','#b2182b','#d6604d','#f4a582','#fddbc7','#f7f7f7','white'))
breaks <- seq(0, 0.8, length.out = length(color))
color <- circlize::colorRamp2(breaks, color)
df_significant_fdr <- t(df_p)[rownames(df), colnames(df)]

ht <- Heatmap(df, 
              name = 'spearman cor',
              col = color,
              rect_gp = gpar(col = "black", lwd = 1),
              cluster_columns = F, cluster_rows = F,
              show_row_dend = F, show_column_dend = F, 
              show_row_names = T, show_column_names = T,
              row_names_side = "left",
              border = F,
              show_heatmap_legend = T,
              use_raster = F)
pdf(paste0(out.dir, 'cor_motif_disruption_score versus effect_size_mash_QTL_adjp0dot05.pdf'), height = 6, width = 20)
draw(ht, padding = unit(c(.1, .1, .1, .1), "npc"))
dev.off()
```

```{r}
saveRDS(df_cor, paste0(out.dir, 'df_cor.rds'))
saveRDS(df_p, paste0(out.dir, 'df_adjP.rds'))
```

































