---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(Seurat)
library(ArchR)
source('~/yuzhao1/scripts/plot.R')
```

```{r, include = F, eval=F}
source('~/yuzhao1/work/atac_gca2024/scripts/gca_colors.R')
source('~/yuzhao1/work/final_GCArna/scripts/gca_markers.R')
out.dir <- '~/yuzhao1/work/atac_gca2024/0manu/plots/1atac_annotation_GSM_Heatmap/'
```


###################### 1. union ########################

```{r, include = F, eval=F}
proj.union <- loadArchRProject(path = "~/yuzhao1/work/atac_gca2024/0dataset/5kmin_6TSS_DoubletRatio2_filtered1/")
gim <- readRDS('~/yuzhao1/work/atac_gca2024/0dataset/5kmin_6TSS_DoubletRatio2_filtered1/GeneIntegrationMatrix.rds')
```

```{r}
gim.genes <- gim@elementMetadata$name
gim.mtx <- gim@assays@data$GeneIntegrationMatrix
rownames(gim.mtx) <- gim.genes
```


```{r}
top10 <- readRDS('~/yuzhao1/work/atac_gca2024/0manu/plots/1rna_annotation_UnionHeatmap/top10.rds')
```

```{r}


anno1.order <- names(gca.rna.unionHeatmap.markers)

top10_combined <- do.call(rbind, top10)
genes <- list()
for (anno1 in anno1.order) {
  genes[[anno1]] <- top10_combined$gene[which(top10_combined$cluster==anno1)]
}

genes[['CD103+ CD8']] <- c('ITGAE', genes[['CD103+ CD8']])
genes[['KLRG1+ CD8']] <- c('KLRG1', genes[['KLRG1+ CD8']])
genes[['GC B']] <- c('BCL6', genes[['GC B']])
genes[['Memory B']] <- c('CD27', genes[['Memory B']])
genes[['Neutrophil']] <- c('FCGR3B', genes[['Neutrophil']])
genes <- genes[anno1.order]
genes <- unique(genes %>% unlist())

genes <- intersect(genes, rownames(gim.mtx))
```


```{r}
seurat <- CreateSeuratObject(counts = gim.mtx[genes,],
                             meta.data = as.data.frame(proj.union@cellColData))
```

```{r}
Average.expression.mtx <- AverageExpression(
  seurat,
  assays = 'RNA',
  features = genes,
  return.seurat = FALSE,
  group.by = "anno1",
  add.ident = NULL,
  slot = "data",
  verbose = TRUE
)
Average.expression.mtx <- Average.expression.mtx$RNA %>% t(.) %>% scale(.) %>% t(.)
Average.expression.mtx <- Average.expression.mtx[genes, names(gca_colors_atac_union_anno1)] # make sure the matrix is in desired order
```


```{r, fig.height=15, fig.width=4}
library(ComplexHeatmap)
library(RColorBrewer)
# show some labels in labels of heatmap
labels <- gca.rna.unionHeatmap.markers %>% unlist() %>% intersect(., rownames(gim.mtx))
labels.idx <- match(labels, rownames(Average.expression.mtx))

pal <- ArchRPalettes$solarExtra
threshold  <- 2
col_fun <- colorRamp2(seq(-threshold, threshold, 2*threshold/(length(pal)-1)), pal)

pdf(paste0(out.dir, 'atac_heatmap_', '_union.pdf'), width = 7, height = 9)
p1 <- Heatmap(Average.expression.mtx, col=col_fun,
              column_split = factor(c(rep('epithelial', 12),
                                    rep('immune', 13),
                                    rep('stromal',4)),
                                    levels = c('epithelial', 'immune', 'stromal')),
              column_title = NULL,
              row_gap = unit(0, "mm"), column_gap = unit(0, "mm"), 
              border = T,
              border_gp = gpar(col = "black", lty = 1, lwd = 1),
              
              cluster_columns = F, show_column_dend = F,
              column_names_gp = gpar(fontsize = 8),
              cluster_rows = F, show_row_dend = F, 
              show_row_names = F,
              heatmap_legend_param = list(title = "Mean expression z score"),
              use_raster = F)+
  rowAnnotation(link = anno_mark(at = labels.idx, labels = labels, labels_gp = gpar(col = "black", fontsize = 6)), 
                width = unit(0.1, "cm") + 
                max_text_width(labels))

print(p1)
dev.off()
```





