---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(data.table)
library(dplyr)
library(stringr)
library(GenomicRanges)
library(bigsnpr)
library(mapgen)
library(susieR)
library(data.table)
library(Repitools)
library(ArchR)
source('~/yuzhao1/scripts/plot.R')
source('~/yuzhao1/work/final_GCArna/scripts/gca_colors.R')
source('~/yuzhao1/scripts/helper_archr.R')
plot.dir <- '~/yuzhao1/work/atac_gca2024/0manu/plots/3snps_susie_L10_locus/'
```

```{r}
proj <- loadArchRProject(path = "~/yuzhao1/work/atac_gca2024/0dataset/5kmin_6TSS_DoubletRatio2_filtered1/")
```


```{r}
gwas_finemapped <- read.csv('~/yuzhao1/work/atac_gca2024/19rasqual/8LDoverlap/gwas_cd/cd_finemapping_unifprior_95loci_L10_annotated.csv', row.names = 1)
gwas_finemapped$pip <- gwas_finemapped$susie_pip
risk_loci_IDs <- unique(gwas_finemapped$locus)
df_RiskSNPs <- gwas_finemapped
df_RiskSNPs$chr <- paste0('chr', df_RiskSNPs$chr)
```

```{r}
############ 2. read locus information (hg19) ############
# hg19 locus
locus_all <- readRDS('~/yuzhao1/work/final_GCAatac/8susie/LD_blocks_mapgen/LD_Blocks.rds') %>% as.data.frame(.)
colnames(locus_all) <- c('chr', 'start', 'end', 'locus_id')
locus_all$chr <- paste0('chr', locus_all$chr)
loci_risk <- locus_all[locus_all$locus_id %in% risk_loci_IDs, ]

risk_loci_chr <- loci_risk[, 'chr']
risk_loci_start <- loci_risk[, 'start']
risk_loci_end <- loci_risk[, 'end']
gr_loci <- GRanges(seqnames = risk_loci_chr, ranges = IRanges(start = risk_loci_start, end = risk_loci_end))
loci_names <- paste0('locus_', loci_risk$locus_id)
```

```{r}
############ 3. read peakset bed files (hg19) ############
peaksets <- list()

# all peaks
xx.df <- read.table('~/yuzhao1/work/atac_gca2024/14ldsc/results/union_peakset/bed_lifted/union_peakset.bed')
colnames(xx.df) <- c('chr', 'start', 'end')
peaksets[['cCREs']] <- xx.df

# cell type specific peakset  
beds_dir <- '~/yuzhao1/work/atac_gca2024/14ldsc/results/healthy_union_anno1_peaks_FDR0_1FC0_5/bed_lifted/'
xx_names <- list.files(beds_dir, full.names = F)
for (xx in xx_names) {
  xx.path <- paste0(beds_dir, xx)
  xx.df <- read.table(xx.path)
  colnames(xx.df) <- c('chr', 'start', 'end')
  peaksets[[xx]] <- xx.df
}
peakset_names <- names(peaksets)

# assign lineage specific peakset (use '@' instead of '_' because some chr are rare)
adaptive_celltypes <- c( "CD4T", "CD8T", "gdT", "GC_B", "NaiveB", "MemoryB", "Plasma")
innate_celltypes <- c("NK", "ILCs", "Mast", "Macrophage", "DC","Neutrophil")

epithelial_peaksets <- peaksets[paste0(names(gca_colors_atac_epithelial_anno1), '.bed')]
epithelial_peaks <- lapply(epithelial_peaksets, function(x) paste0(x[[1]], '@', x[[2]], '@', x[[3]])) %>% unlist() %>% unique()
immune_peaksets <- peaksets[paste0(names(gca_colors_atac_immune_anno1), '.bed')]
immune_peaks <- lapply(immune_peaksets, function(x) paste0(x[[1]], '@', x[[2]], '@', x[[3]])) %>% unlist() %>% unique()
adaptive_peaksets <- peaksets[paste0(adaptive_celltypes , '.bed')]
adaptive_peaks <- lapply(adaptive_peaksets, function(x) paste0(x[[1]], '@', x[[2]], '@', x[[3]])) %>% unlist() %>% unique()
innate_peaksets <- peaksets[paste0(innate_celltypes , '.bed')]
innate_peaks <- lapply(innate_peaksets, function(x) paste0(x[[1]], '@', x[[2]], '@', x[[3]])) %>% unlist() %>% unique()
stromal_peaksets <- peaksets[paste0(names(gca_colors_atac_stromal_anno1), '.bed')]
stromal_peaks <- lapply(stromal_peaksets, function(x) paste0(x[[1]], '@', x[[2]], '@', x[[3]])) %>% unlist() %>% unique()

all_lineage_peaks <- c(epithelial_peaks, immune_peaks, stromal_peaks)
lineage_shared_peaks <- names(table(all_lineage_peaks)[table(all_lineage_peaks) > 1])
epithelial_peaks <- setdiff(epithelial_peaks, lineage_shared_peaks)
immune_peaks <- setdiff(immune_peaks, lineage_shared_peaks)
stromal_peaks <- setdiff(stromal_peaks, lineage_shared_peaks)

adaptive_innate_shared_peaks <- intersect(adaptive_peaks, innate_peaks)
adaptive_innate_shared_peaks <- setdiff(adaptive_innate_shared_peaks, lineage_shared_peaks)

adaptive_peaks <- setdiff(adaptive_peaks, adaptive_innate_shared_peaks)
adaptive_peaks <- setdiff(adaptive_peaks, lineage_shared_peaks)
innate_peaks <- setdiff(innate_peaks, adaptive_innate_shared_peaks)
innate_peaks <- setdiff(innate_peaks, lineage_shared_peaks)

df_epithelial <- data.frame(chr = epithelial_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,1),
                            start = epithelial_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,2) %>% as.numeric(),
                            end = epithelial_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,3) %>% as.numeric())
df_stromal <- data.frame(chr = stromal_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,1),
                         start = stromal_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,2) %>% as.numeric(),
                         end = stromal_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,3) %>% as.numeric())
df_shared <- data.frame(chr = lineage_shared_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,1),
                         start = lineage_shared_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,2) %>% as.numeric(),
                         end = lineage_shared_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,3) %>% as.numeric())
df_adaptive <- data.frame(chr = adaptive_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,1),
                        start = adaptive_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,2) %>% as.numeric(),
                        end = adaptive_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,3) %>% as.numeric())
df_innate <- data.frame(chr = innate_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,1),
                        start = innate_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,2) %>% as.numeric(),
                        end = innate_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,3) %>% as.numeric())
df_adaptive_innate_shared <- data.frame(chr = adaptive_innate_shared_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,1),
                        start = adaptive_innate_shared_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,2) %>% as.numeric(),
                        end = adaptive_innate_shared_peaks %>% strsplit(split = '@', fixed=T) %>% sapply(.,`[[`,3) %>% as.numeric())

peaksets <- list(epithelial = df_epithelial,
                 stromal = df_stromal,
                 adaptive = df_adaptive,
                 innate = df_innate,
                 adaptive_innate_shared = df_adaptive_innate_shared,
                 lineage_shared = df_shared,
                 cCREs = peaksets[['cCREs']])
peakset_names <- names(peaksets)



```

```{r}
# assign score
score_celltype_locus <- data.frame(matrix(0, nrow = nrow(loci_risk), ncol = length(peakset_names)))
rownames(score_celltype_locus) <- loci_names
colnames(score_celltype_locus) <- peakset_names


for (i in 1:nrow(df_RiskSNPs)) {
  snp_chr <- df_RiskSNPs[i, 'chr']
  snp_pos <- df_RiskSNPs[i, 'pos']
  snp_pip <- df_RiskSNPs[i, 'pip']
  gr_snp <- GRanges(seqnames = snp_chr, ranges = IRanges(start = snp_pos, end = snp_pos))
  cat(paste0('working on snp: ', i, ' out of ', nrow(df_RiskSNPs), '\n'))
  
  overlaps <- findOverlaps(gr_snp, gr_loci)
  risk_locus_name <-  loci_names[overlaps@to]

  for (k in 1:ncol(score_celltype_locus)) {
    peaks_set_temp <- peaksets[[k]]
    gr_peakset <- GRanges(seqnames = peaks_set_temp$chr, ranges = IRanges(start = peaks_set_temp$start, end = peaks_set_temp$end))

    if(any(findOverlaps(gr_snp, gr_peakset)@from)){
      # update score
      cat(paste0('updating score: ', i, ' * ', k, '\n'))
      score_celltype_locus[risk_locus_name, k] <- score_celltype_locus[risk_locus_name, k] + snp_pip
    }
  }
}

saveRDS(score_celltype_locus, '~/yuzhao1/work/atac_gca2024/0manu/plots/3snps_susie_L10_locus/score_lineage_locus.rds')
score_celltype_locus <- readRDS('~/yuzhao1/work/atac_gca2024/0manu/plots/3snps_susie_L10_locus/score_lineage_locus.rds')
```

```{r}
p <- ggplot(score_celltype_locus, aes(x=cCREs))+
    geom_histogram(fill="#69b3a2", color="black", alpha=0.9, breaks=seq(0,3.6,0.1)) +
    theme_pubr() + # Use ggpubr theme
    geom_vline(xintercept = 0.2, color = "black", lwd=0.5, linetype="dashed") +
    scale_y_continuous(breaks = seq(5,30,5))+
    theme(axis.title = element_text(size = 15, face = 'bold'),
          axis.text.y = element_text(size = 15),
          axis.text.x = element_text(size = 15),
          plot.title = element_text(hjust = 0.5),
          legend.position = "bottom")+
  labs(title = "", x = "pip sum", y = "# Loci") 

pdf(paste0(plot.dir, 'pip_all_cCREs_with_0.2Line_lineage.pdf'), width = 7, height = 5)
print(p)
dev.off()
```

```{r}
# filter by sum all pips in cCREs without duplicated counting
df <- score_celltype_locus
df <- df[df$cCREs > 0.2, ]
df$cCREs <- NULL
df_normalized <- t(df)
```

```{r}
df_ID_hg19name <- read.table('/project/gca/yuzhao1/work/final_GCAatac/8susie/LD_blocks_mapgen/locus_all_hg19.bed')
colnames(df_ID_hg19name) <- c('chr', 'start', 'end', 'locus_id')
df_ID_hg19name$locus_id <- paste0('locus_', df_ID_hg19name$locus_id)
df_ID_hg19name$locus_plot <- paste0(df_ID_hg19name$chr, ':', df_ID_hg19name$start, '-', df_ID_hg19name$end)
colnames(df_normalized) <- mapvalues(colnames(df_normalized), df_ID_hg19name$locus_id, df_ID_hg19name$locus_plot, warn_missing = F)
```

```{r}

color = c('white', '#B41658FF')
breaks <- seq(0, 0.2, length.out = length(color))
col_fun <- circlize::colorRamp2(breaks, color)



# column_ha <- HeatmapAnnotation(foo = anno_text(colnames(df_normalized), location = 1, rot = 45, 
#                                                gp = gpar(fontsize = 10, fontface='bold')))

pdf(paste0(plot.dir, 'locus_partition_lineage_cCRE_pip_sum_cutoff_0.2.pdf'), height = 4.3, width = 12)
ht <- Heatmap(df_normalized, 
              name = 'pip sum',
              # bottom_annotation = column_ha,
              col = col_fun,
              rect_gp = gpar(col = "black", lwd = 1),
              # cell_fun = function(j, i, x, y, width, height, fill) {
              #   grid.text(sprintf("%.2f", df_normalized[i, j]), x, y, gp = gpar(fontsize = 10))
              # },
              cluster_columns = T, cluster_rows = F,
              show_row_dend = F, show_column_dend = F, 
              show_row_names = T, show_column_names = T,
              row_names_side = "left",
              border = T,
              use_raster = F,
              show_heatmap_legend = T)
draw(ht, padding = unit(c(.1, .1, .1, .1), "npc"))
dev.off()



```


















