---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(Seurat)
library(ArchR)
library(Repitools)
library(readxl)  
library(ComplexHeatmap)
library(readxl)    

source('~/yuzhao1/scripts/plot.R')
source('~/yuzhao1/work/atac_gca2024/scripts/gca_colors.R')
source('~/yuzhao1/work/final_GCArna/scripts/gca_markers.R')
out.dir <- '~/yuzhao1/work/atac_gca2024/0manu/plots/6dar_TF_enrichment/'
```

```{r}
## read inf peaks
filename <- '~/yuzhao1/work/atac_gca2024/7dreamlet/differential_test/tfs_inf_vs_control_allCelltypes_FC05_adjP01_healthy.xlsx'
sheets <- readxl::excel_sheets(filename)
x <- lapply(sheets, function(X) readxl::read_excel(filename, sheet = X))
x <- lapply(x, as.data.frame)
names(x) <- sheets
TF_df_list <- x
rm(x)

# initialize a df
TFs_names <- TF_df_list$AC_Goblet$feature %>% strsplit(., split = '_', fixed=T) %>% sapply(.,`[[`,1)
TF_df_all <- as.data.frame(matrix(0, nrow = 870, ncol = length(TF_df_list)))
rownames(TF_df_all) <- TFs_names
colnames(TF_df_all) <- names(TF_df_list)

```


```{r}
# no further filter with gene score/ gene corr yet
# use these mlogP
TF_clusters <- readRDS('~/yuzhao1/work/atac_gca2024/5TF/2TF_clustering/300clusters.rds')
TF_cutOff <- 2
max_n_TFs_perCt <- 50
max_TF_adjP_cap <- 5
TFs_selected <- c()
cts_noTF <- c()

for (i in 1:length(TF_df_list)){
  topic_name <- names(TF_df_list)[[i]]
  tmp_enr <- TF_df_list[[topic_name]]
  tmp_enr$feature <- tmp_enr$feature %>% strsplit(., split = '_', fixed=T) %>% sapply(.,`[[`,1)
  rownames(tmp_enr) <- tmp_enr$feature 
  tmp_enr <- tmp_enr[order(tmp_enr$mlog10Padj, decreasing = T), ]
  
  xx <- tmp_enr[tmp_enr$mlog10Padj>TF_cutOff, 'feature']
  
  if(length(xx) < 1){
    cts_noTF <- c(cts_noTF, topic_name)
    cat(topic_name, ': no TF passed TF cutoff\n')
    next
  }
  
  if(length(xx) > max_n_TFs_perCt){
    xx <- xx[1:max_n_TFs_perCt]
  }
  xx <- xx[!is.na(xx)]
  
  # add all TFs that are clustered together
  clusters_significant <- unique(TF_clusters[xx])
  xx <- names(TF_clusters)[TF_clusters %in% clusters_significant]

  # # filter by top gene score
  # xx <- intersect(TFs_topGeneScore[, topic_name], xx)
  
  TFs_selected <- unique(c(TFs_selected, xx))
  
  # add raw data to main df
  TF_df_all[, topic_name] <- tmp_enr[rownames(TF_df_all), 'mlog10Padj']
}

TFs_selected <- unique(TFs_selected)
TF_df_all <- TF_df_all[, !colnames(TF_df_all) %in% cts_noTF]
TF_df_all <- TF_df_all[TFs_selected, colnames(TF_df_all)[order(match(names(TF_df_all), names(gca_colors_atac_union_anno1)))]]

```

```{r}
df_TF_regulator <- readRDS('/project/gca/yuzhao1/work/atac_gca2024/5TF/output/union/regulator_df_anno1_inflammation_status_location_cor0.4_delta0.25.rds')
TF_positive <- df_TF_regulator[df_TF_regulator$TFRegulator=='Positive', 'cisbp_matchName']
TFs_selected <- intersect(TF_positive, TFs_selected)


df <- t(TF_df_all[TFs_selected, ])
df <- df[, mixedsort(colnames(df))]

for (i in 1:nrow(df)) {
  xx <- df[i,]
  xx[xx>max_TF_adjP_cap] <- max_TF_adjP_cap 
  df[i, ] <- xx/max(xx, 0.01) # avoid NA and all zero rows
}
df <- df+0.001 # avoid NA and all zero rows
```


```{r}
transposed_df <- t(df)
# scaled_df <- scale(transposed_df)
set.seed(6)  
num_clusters <- 20
kmeans_result <- kmeans(transposed_df, centers = num_clusters)
cluster_assignments <- kmeans_result$cluster
```

```{r}
# Unique clusters
clusters <- 1:num_clusters

# Initialize a vector to store the row assignment for each cluster
cluster_row_assignment <- setNames(rep(NA, length(clusters)), clusters)

# Calculate the mean for each cluster in each row and find the row with the highest mean
for (cluster in clusters) {
  # Columns belonging to the current cluster
  cluster_cols <- names(cluster_assignments)[cluster_assignments == cluster]
  
  # Calculate the mean for these columns in each row
  cluster_means <- apply(df[, cluster_cols, drop = FALSE], 1, mean)
  
  # Find the row with the maximum mean
  cluster_row_assignment[[cluster]] <- which.max(cluster_means)
}


# sort clusters by row_assignment
xx <- names(cluster_row_assignment)[order(cluster_row_assignment, decreasing = F)]
ordered_columns <- unlist(lapply(xx, function(cluster) {
  names(cluster_assignments)[cluster_assignments == cluster]
}))
df <- df[, ordered_columns]
```

```{r}
library(circlize)
color = c('white', '#3690c0')
breaks <- seq(0, 1, length.out = length(color))
color <- circlize::colorRamp2(breaks, color)


ht <- Heatmap(df, 
              name = 'scaled mlog(adjp)',
              col = color,
              rect_gp = gpar(col = "black", lwd = 1),
              cluster_columns = F, cluster_rows = F,
              show_row_dend = F, show_column_dend = F, 
              show_row_names = T, show_column_names = T,
              row_names_side = "left",
              border = F,
              show_heatmap_legend = T,
              use_raster = F)


pdf(paste0(out.dir, 'TF_cutoff2_maxN50_cap5_healthy.pdf'), height = 4.5, width = 15)
draw(ht, padding = unit(c(.1, .1, .1, .1), "npc"))
dev.off()
```




















