---
title: "Raw data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='hide', message=FALSE, warning=FALSE, fig.height = 7, fig.width = 7)
dyn.load('/software/geos-3.9.1-el8-x86_64/lib64/libgeos_c.so')
library(ggplot2)
library(dplyr)
library(plyr)
library(stringr)
library(Seurat)
library(ArchR)
library(Repitools)
library(readxl)  
library(ComplexHeatmap)

source('~/yuzhao1/scripts/plot.R')
source('~/yuzhao1/work/atac_gca2024/scripts/gca_colors.R')
source('~/yuzhao1/work/final_GCArna/scripts/gca_markers.R')
out.dir <- '~/yuzhao1/work/atac_gca2024/0manu/plots/6dar_count_linkedGene_and_select_TrackPlot/'
```

```{r}
filenames <-c('~/yuzhao1/work/atac_gca2024/7dreamlet/differential_test/peaks_inf_vs_control_allCelltypes_FC05_adjP01.xlsx')
contrast_names <- c('inf_vs_control') 

peaks_all_contrasts_list <- list()

for (i in 1:1) {
  filename <- filenames[[i]]
  sheets <- readxl::excel_sheets(filename)
  x <- lapply(sheets, function(X) readxl::read_excel(filename, sheet = X, col_names = F))
  x <- lapply(x, as.data.frame)
  names(x) <- sheets
  peaks_all_contrasts_list[[contrast_names[[i]]]] <- x
}
```

```{r}
# statistics and its peakname
raw_statistics <- readRDS('~/yuzhao1/work/atac_gca2024/7dreamlet/differential_test/statistics_inf_vs_control.rds')
peaks_raw_statistics <- readRDS('~/yuzhao1/work/atac_gca2024/0dataset/5kmin_6TSS_DoubletRatio2_filtered1/peakMtx_unbinarized_rowranges.rds')

# selected peaks
peakset_abc <- readRDS('~/yuzhao1/work/atac_gca2024/0dataset/5kmin_6TSS_DoubletRatio2_filtered1/peakMtx_unbinarized_rowranges_abc_annotated.rds')
peakset_archr <- readRDS('~/yuzhao1/work/atac_gca2024/0dataset/5kmin_6TSS_DoubletRatio2_filtered1/peakSet.rds')
peakset_archr <- peakset_archr %>% data.frame() 
rownames(peakset_archr) <- paste0(peakset_archr$seqnames, '_', peakset_archr$start, '_', peakset_archr$end)

# read important TFs
df_TF_regulator <- readRDS('/project/gca/yuzhao1/work/atac_gca2024/5TF/output/union/regulator_df_anno1_inflammation_status_location_cor0.4_delta0.25.rds')
TF_positive <- df_TF_regulator[df_TF_regulator$TFRegulator=='Positive', 'cisbp_matchName']
```

# iDAR

```{r}
# a table containing inf peaks overlapping with ABC peaks
df_list <- list()
for (ct in names(peaks_all_contrasts_list$inf_vs_control)) {
  t_statistics <- raw_statistics[[ct]]
  t_statistics_rowname_gr <- peaks_raw_statistics[as.numeric(rownames(t_statistics)),] %>% data.frame()
  rownames(t_statistics) <- paste0(t_statistics_rowname_gr$seqnames, '_', 
                                   t_statistics_rowname_gr$start, '_', 
                                   t_statistics_rowname_gr$end)
  
  ct_peaks <- peaks_all_contrasts_list$inf_vs_control[[ct]][[1]]
  df_abc <- peakset_abc[peakset_abc$archr_peak %in% ct_peaks,]
  df_abc$archrpeak_logFC <- t_statistics[df_abc$archr_peak, 'logFC'] 
  df_abc$archrpeak_adj.P.Val <- t_statistics[df_abc$archr_peak, 'adj.P.Val'] 
  df <- df_abc[, c( "archr_peak", "archrpeak_logFC", "archrpeak_adj.P.Val", 
                    "ABC_name", "ABC_TargetGene", "ABC_ABC.Score", "ABC_CellType")]
  colnames(df) <- c('peak_OurStudy_hg38', 'inf_vs_control_logFC', 'inf_vs_control_adjusted_p',
                    'ABC_peak_hg19', 'ABC_peakTargetGene', 'ABC_score', 'ABC_cellType')
  if(nrow(df) < 1){
    next # no peak has linked ABC peak
  }
  df$celltype_specificity_for_inf_vs_control_contrast_in_ourStudy <- ct
  df <- df[, c('celltype_specificity_for_inf_vs_control_contrast_in_ourStudy',
               'peak_OurStudy_hg38', 'inf_vs_control_logFC', 'inf_vs_control_adjusted_p',
               'ABC_peak_hg19', 'ABC_peakTargetGene', 'ABC_score', 'ABC_cellType')]
  rownames(df) <- NULL
  df_list[[ct]] <- df
}
df_abc <- bind_rows(df_list)
```

```{r}
# a table containing all dars
df_list <- list()
for (ct in names(peaks_all_contrasts_list$inf_vs_control)) {
  t_statistics <- raw_statistics[[ct]]
  t_statistics_rowname_gr <- peaks_raw_statistics[as.numeric(rownames(t_statistics)),] %>% data.frame()
  rownames(t_statistics) <- paste0(t_statistics_rowname_gr$seqnames, '_', 
                                   t_statistics_rowname_gr$start, '_', 
                                   t_statistics_rowname_gr$end)
  
  ct_peaks <- peaks_all_contrasts_list$inf_vs_control[[ct]][[1]]
  t_statistics <- t_statistics[ct_peaks, ]
  t_statistics[, c("nearestGene", "peakType")] <- peakset_archr[rownames(t_statistics), c("nearestGene", "peakType")]
  df <- t_statistics[, c('peakType', 'nearestGene', 'logFC', 'adj.P.Val')]
  colnames(df) <- c('peakType', 'nearestGene', "inf_vs_control_logFC", "inf_vs_control_adjusted_p")
    
  df$celltype_specificity_for_inf_vs_control_contrast_in_ourStudy <- ct
  df$peak_OurStudy_hg38 <- rownames(df)
  df <- df[, c("celltype_specificity_for_inf_vs_control_contrast_in_ourStudy", 
               "peak_OurStudy_hg38", "inf_vs_control_logFC", "inf_vs_control_adjusted_p", 
               "nearestGene", "peakType" )]
  rownames(df) <- NULL
  

  df_list[[ct]] <- df
}
df_archr <- bind_rows(df_list)
```

# cell type specific dar

```{r}
df_ctDAR <- readRDS('~/yuzhao1/work/atac_gca2024/4peaks/DARs/healthy_union_anno1_peaks/FDR0_1FC0_5_peak_cellType_table.rds')
```


```{r}
library(openxlsx)
xx <- list('inflammation associated DARs' = df_archr, 
           'iDARs overlapped with ABC peaks' = df_abc,
           'cell type specific DARs' = df_ctDAR)
write.xlsx(xx, overwrite = T,
           file = paste0('~/yuzhao1/work/atac_gca2024/0manu/supplementary_table/',
                         'Inflammation associated DARs and Cell type specific DARs.xlsx'))
```
















