cd ~/yuzhao1/work/atac_gca2024/20bam
sbatch -J AC_Goblet --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/AC_Goblet.out --error=2.2vcf_celltype/log/AC_Goblet.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/AC_Goblet.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/AC_Goblet.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/AC_Goblet.vcf.gz'
sbatch -J AC_Stem --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/AC_Stem.out --error=2.2vcf_celltype/log/AC_Stem.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/AC_Stem.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/AC_Stem.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/AC_Stem.vcf.gz'
sbatch -J BEST4 --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/BEST4.out --error=2.2vcf_celltype/log/BEST4.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/BEST4.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/BEST4.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/BEST4.vcf.gz'
sbatch -J CD4T --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/CD4T.out --error=2.2vcf_celltype/log/CD4T.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/CD4T.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/CD4T.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/CD4T.vcf.gz'
sbatch -J CD8T --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/CD8T.out --error=2.2vcf_celltype/log/CD8T.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/CD8T.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/CD8T.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/CD8T.vcf.gz'
sbatch -J Colonocyte --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/Colonocyte.out --error=2.2vcf_celltype/log/Colonocyte.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/Colonocyte.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Colonocyte.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Colonocyte.vcf.gz'
sbatch -J Early_Colonocyte --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/Early_Colonocyte.out --error=2.2vcf_celltype/log/Early_Colonocyte.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/Early_Colonocyte.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Early_Colonocyte.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Early_Colonocyte.vcf.gz'
sbatch -J Early_Enterocyte --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/Early_Enterocyte.out --error=2.2vcf_celltype/log/Early_Enterocyte.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/Early_Enterocyte.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Early_Enterocyte.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Early_Enterocyte.vcf.gz'
sbatch -J Endothelium --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/Endothelium.out --error=2.2vcf_celltype/log/Endothelium.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/Endothelium.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Endothelium.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Endothelium.vcf.gz'
sbatch -J Enterocyte --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/Enterocyte.out --error=2.2vcf_celltype/log/Enterocyte.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/Enterocyte.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Enterocyte.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Enterocyte.vcf.gz'
sbatch -J Fibroblast --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/Fibroblast.out --error=2.2vcf_celltype/log/Fibroblast.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/Fibroblast.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Fibroblast.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Fibroblast.vcf.gz'
sbatch -J Macrophage --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/Macrophage.out --error=2.2vcf_celltype/log/Macrophage.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/Macrophage.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Macrophage.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Macrophage.vcf.gz'
sbatch -J MemoryB --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/MemoryB.out --error=2.2vcf_celltype/log/MemoryB.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/MemoryB.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/MemoryB.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/MemoryB.vcf.gz'
sbatch -J NaiveB --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/NaiveB.out --error=2.2vcf_celltype/log/NaiveB.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/NaiveB.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/NaiveB.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/NaiveB.vcf.gz'
sbatch -J Neutrophil --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/Neutrophil.out --error=2.2vcf_celltype/log/Neutrophil.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/Neutrophil.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Neutrophil.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Neutrophil.vcf.gz'
sbatch -J Plasma --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/Plasma.out --error=2.2vcf_celltype/log/Plasma.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/Plasma.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Plasma.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/Plasma.vcf.gz'
sbatch -J TI_Goblet --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/TI_Goblet.out --error=2.2vcf_celltype/log/TI_Goblet.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/TI_Goblet.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/TI_Goblet.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/TI_Goblet.vcf.gz'
sbatch -J TI_Stem --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/TI_Stem.out --error=2.2vcf_celltype/log/TI_Stem.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/TI_Stem.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/TI_Stem.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/TI_Stem.vcf.gz'
sbatch -J gdT --time=36:00:00 --mem=5Gb --output=2.2vcf_celltype/log/gdT.out --error=2.2vcf_celltype/log/gdT.err --account=pi-spott  -p spott -c 1 --wrap='bcftools view -Oz -S ~/yuzhao1/work/atac_gca2024/19rasqual/0patientID_perCelltype/gdT.txt ~/yuzhao1/work/final_GCAatac/18glimpse/7.1snps_filter/allPatients_filtered.vcf.gz > ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/gdT.vcf.gz
bcftools index ~/yuzhao1/work/atac_gca2024/20bam/2.2vcf_celltype/vcf_perCelltype_filtered_patients/gdT.vcf.gz'
